### ISSUE TITLE
Fix missing promoFieldObject context on promoClick events

### ISSUE THREAD

**Issue by akurnosov** [snowplow/snowplow-gtm-tag-template-v3#23]
![image](https://user-images.githubusercontent.com/32516973/229141346-4f5518a6-6c6e-4f4c-9643-9a337464ccbf.png)

when you push promoView event - everything is ok
![Снимок экрана 2023-03-31 в 17 04 47](https://user-images.githubusercontent.com/32516973/229142517-2ddd3c4d-6546-4141-9f12-7bb4843e2544.png)

`window.dataLayer.push({
  event: 'eec.promotionView',
  ecommerce: {
    promoView: {
      promotions: [{
        id: 'summer_campaign',
        name: 'Summer Campaign 2019',
        creative: 'Front Page Carousel',
        position: 'Slide 1'
      },{
        id: 'fall_campaign',
        name: 'Fall Campaign 2019',
        creative: 'Front Page Carousel',
        position: 'Slide 2'
      }]
    }
  }
});`

when you push promoClick event:

`window.dataLayer.push({
  event: 'eec.promotionClick',
  ecommerce: {
    promoClick: {
      promotions: [{
        id: 'fall_campaign',
        name: 'Fall Campaign 2019',
        creative: 'Front Page Carousel',
        position: 'Slide 2'
      }]
    }
  }
});`

there is no part:
contexts_com_google_analytics_enhanced-ecommerce_promo_field_object_1
![image](https://user-images.githubusercontent.com/32516973/229142904-903a5b65-41e4-4e76-8f6d-b66b71c20895.png)

**Comment by adatzer** [comment]
Hello @akurnosov !
Thank you very much for reporting this issue. A fix is included in #25  aiming for the next release of the tag.
