### ISSUE TITLE
Unable to Add Additional Contexts to Event with Snowplow GTM Template Version 2.0.x

### ISSUE THREAD

**Issue by mylifeasdog** [snowplow/snowplow-gtm-tag-template-v3#27]
### Description
After updating the Snowplow GTM template to version 2.0.1, I am unable to add additional contexts to the event. This issue appears to have started since version 2.0.0.

### Expected Behavior:
Before updating to 2.0.0, I was able to create a JavaScript variable that returned an array of context objects and it worked as expected.

### Current Behavior:
Since migrating to 2.0.0 and also in 2.0.1, the additional contexts are still shown as being sent in the GTM preview. However, when inspecting the browser's network traffic, no additional contexts are actually being sent. Additionally, when I view the variable within GTM, it indicates that it is still linked to the tag. However, once I click on the tag, the variable is not displayed as being used. When I attempt to add the same variable to the same tag again and save it, the system indicates that it needs to be a table. How should I proceed to resolve this issue?
![Screenshot 2023-06-28 at 14 36 04](https://github.com/snowplow/snowplow-gtm-tag-template-v3/assets/749739/1118cbbf-53af-49a5-99e8-2e70b35be4f4)

**Comment by adatzer** [comment]
Hello @mylifeasdog !
This comes from the fact the the automatic updates UI could not handle the change (which is the reason we went for a major version bump).
The context entities [is now a table](https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/google-tag-manager-custom-template/template-for-javascript-tracker-v3/tag-template-guide/#additional-tracking-parameters).
However you can still use the same variable as before.
Currently, the way to resolve this would be to remove the variable, then click on `Add Row` and re-add it.
Please, let us know if this resolves the issue.

**Comment by mylifeasdog** [comment]
Thank you for the response.

I understand from your explanation that I need to remove the variable, click on "Add Row", and then re-add it to resolve the issue. However, when I click on the referenced tag on the variable, there is no option or any elements there that I can delete.

In the screenshot attached to my initial post, I displayed the state after re-adding the variable and saving. Additionally, I am attaching another photo below, which shows the state of the tag just after I click on the referenced tag. As you can see, there is nothing there that allows me to delete the old value.

From what you explained, it seems like the error is not due to the new value that I added to the context entities but rather due to the old value, which is not visible in the UI. Does this imply that in order to avoid conflicts with this invisible old value, I should create each tag from scratch?

Creating all tags anew could be a time-consuming and error-prone process, especially if there are a significant number of tags involved. Are there any alternate solutions or workarounds that can be employed to streamline this process?


Thank you in advance.

![Screenshot 2023-06-29 at 12 14 24](https://github.com/snowplow/snowplow-gtm-tag-template-v3/assets/749739/e0344993-622f-4c62-87b0-69991803d40e)

**Comment by adatzer** [comment]
Thank you for providing more information @mylifeasdog .
Unfortunately, what happens under the hood is not under our control, so not much of an alternative at this point, other than the one you already suggested (re-implementing). Hopefully this is addressed by GTM in the future.

Still, you could allow for gradual upgrade by disassociating the template from the gallery (e.g. by renaming the **Template** to something like `Snowplow v3 old`), then import the new version from the gallery. This will allow you to have both versions of the template available and proceed to upgrading in a more structured way.
